[package]
name = "hello-wasi-cli"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
package = "component:hello-wasi-cli"

[package.metadata.component.dependencies]

[dependencies]
wit-bindgen = "0.16.0"
