[package]
name = "canonical-abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-rt = "0.24.0"

[lib]
crate-type = ["cdylib", "rlib"]
