package chikoski:glitch-art@0.3.4;

interface png-glitchable {

    enum filter-type {
        none,
        sub,
        up,
        average,
        paeth,
    }

    resource scan-line {
        get-filter-type: func() -> filter-type;
        set-filter-type: func(t: filter-type);
        size: func() -> u32;
        get-pixel-at: func(index: u32) -> u8;
        set-pixel-at: func(index: u32, value: u8);
        read: func() -> result<list<u8>>;
        write: func(pixels: list<u8>);
    }

    resource png {
        get-scan-lines: func() -> list<scan-line>;
        read: func() -> result<list<u8>>;

        create: static func(data: list<u8>) -> result<png>;
    }

}

interface bridge-to-png-glitchable {
    use png-glitchable.{ png, scan-line, filter-type };

    create: func(data: list<u8>, width: u32, height: u32) -> result<png>;
}

world png-glitcher {
    export png-glitchable;
}

world bridge {
    include png-glitcher;

    import png-glitchable;
    export bridge-to-png-glitchable;
}