package component:hello-world;

interface formatter {
    use dimension.{point};

    enum format-error {
        unknown,
        utf8,
    }
    format: func(value: string) -> result<string, format-error>;
    format-point: func(p: point) -> result<string, format-error>;
    id: func(value: string) -> string;
}

interface dimension {
    record point {
        x: s32,
        y: s32,
    }
    new-point: func(x: s32, y: s32) -> point;
}

world example {
    export formatter;
    export dimension;
}
