spin_manifest_version = 2

[application]
name = "hello-world-http-runner"
version = "0.1.0"
authors = ["N.Shimizu <chikoski@gmail.com>"]
description = ""

[[trigger.http]]
route = "/"
component = "hello-world-http"

[component.hello-world-http]
source = "hello_world_http.wasm"
