[package]
name = "host-says"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
package = "component:says"

[package.metadata.component.dependencies]

[package.metadata.component.target]
path = "./wit"
world = "says-runner"

[dependencies]
wit-bindgen = "0.16.0"
